[package]
name = "neural_net"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.6"
log = "0.4.22"
mnist = "0.6.0"
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
rand = "0.8.5"
